pipeline { // Declarative pipelineであることを宣言する
  environment {
    SERVICE_CREDS = credentials('github-credentials')
  }
  agent any
  stages {
    stage('delete workspace') {
        steps {
            deleteDir()
        }
    }
    stage("get resource") {
      steps {
        git(credentialsId: 'github-credentials', url: 'https://github.com/chiruchiruchiru/MyWebpack.git')
      }
      steps {
        echo "＼( 'ω')／ウオオオオオアアアーーーッ！"
      }
    }
  }
}