pipeline { // Declarative pipelineであることを宣言する
  environment {
    SERVICE_CREDS = credentials('github-credentials')
  }
  agent any
  stages {
    stage("get resource") {
      steps {
        git(credentialsId: "${SERVICE_CREDS_USER}", url: 'git@github.com:chiruchiruchiru/MyWebpack.git')
      }
    }
  }
}