pipeline { // Declarative pipelineであることを宣言する
  environment {
    SERVICE_CREDS = credentials('github-credentials')
  }
  agent any
  stages {
    stage("get resource") {
      steps {
        sh "echo ${SERVICE_CREDS}"
        sh "echo ${SERVICE_CREDS_USER}"
        // git(credentialsId: "${SERVICE_CREDS}", url: 'git@github.com:chiruchiruchiru/MyWebpack.git')
      }
    }
  }
}